name: Devops Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar credenciais da AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Instalar o AWS SAM CLI
      - name: Install AWS SAM CLI
        run: |
          if ! command -v sam &> /dev/null; then
            echo "AWS SAM CLI não encontrado. Instalando..."
            sudo apt-get update
            sudo apt-get install -y unzip
            curl -Lo sam-installation.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
            unzip sam-installation.zip -d sam-installation
            sudo ./sam-installation/install
          else
            echo "AWS SAM CLI já está instalado. Pulando instalação."
          fi

      # 4. Instalar dependências do projeto (se necessário)
      - name: Install dependencies
        run: |
          cd AuthenticationFunction
          mvn clean install
          
      # 5. Build do projeto com SAM
      - name: Build with SAM
        run: |
          sam build --template-file template.yaml

      # 6. Deploy para a AWS Lambda
      - name: Deploy Lambda
        run: |
          sam deploy --template-file template.yaml --confirm-changeset
